# Generated by Django 6.0.1 on 2026-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_is_bestseller_book_is_new_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Book is available for sale'),
        ),
        migrations.AddField(
            model_name='book',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this number'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of copies available for sale'),
        ),
    ]
