# Generated by Django 6.0.1 on 2026-04-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_active_book_low_stock_threshold_book_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Set as featured image (overrides main book image)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='books.book')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
