# Generated by Django 6.0.1 on 2026-04-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('book', 'Inappropriate Book'), ('user', 'Suspicious User'), ('review', 'Offensive Review')], default='book', max_length=10)),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('offensive', 'Offensive content'), ('fake', 'Fake product'), ('price', 'Wrong price'), ('copyright', 'Copyright violation'), ('other', 'Other reason')], default='other', max_length=20)),
                ('description', models.TextField(help_text='Please provide detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved - Action Taken')], default='pending', max_length=20)),
                ('action_taken', models.CharField(choices=[('none', 'No action taken'), ('warning', 'Warning issued'), ('deactivated', 'Book/User deactivated'), ('deleted', 'Content deleted'), ('banned', 'User banned')], default='none', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about resolution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='books.book')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reported_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='books.review')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('license', 'Driving License'), ('voter_id', 'Voter ID'), ('other', 'Other ID Proof')], default='aadhar', max_length=20)),
                ('document', models.FileField(help_text='Upload ID proof document (PDF or Image)', upload_to='seller_verifications/')),
                ('document_number', models.CharField(blank=True, help_text='ID document number', max_length=100, null=True)),
                ('additional_document', models.FileField(blank=True, help_text='Additional proof if needed', null=True, upload_to='seller_verifications/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to seller)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Old Book Store', max_length=100)),
                ('site_tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('commission_rate', models.FloatField(default=5.0, help_text='Commission percentage deducted from seller earnings')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=40.0, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock falls below this number')),
                ('out_of_stock_threshold', models.IntegerField(default=0, help_text='Mark as out of stock at this level')),
                ('cancel_deadline_hours', models.IntegerField(default=24, help_text='Hours after which order cannot be cancelled')),
                ('return_days', models.IntegerField(default=7, help_text='Days allowed for returns')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put site in maintenance mode')),
                ('enable_seller_verification', models.BooleanField(default=True, help_text='Require seller verification')),
                ('enable_reviews', models.BooleanField(default=True, help_text='Allow product reviews')),
                ('enable_wishlist', models.BooleanField(default=True, help_text='Enable wishlist feature')),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
